on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11
      - name: Install dependencies
        run: python -m pip install urllib3 && python -m pip install -r requirements.txt --no-cache-dir
      - name: Check license
        run: python .github/workflows/license_checker_v2.py --dependencies $(cut -d '=' -f 1 <<< $(pip freeze))
